# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-20 20:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(max_length=40, null=True, srid=4326),
        ),
    ]
