# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-20 22:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_utilisateur_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noeud',
            fields=[
                ('identifiant_arduino', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.FloatField()),
                ('temperature', models.BooleanField()),
                ('radiation', models.BooleanField()),
                ('humidite_sol', models.BooleanField()),
            ],
            options={
                'db_table': 'noeud',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='projet',
            name='type',
            field=models.CharField(choices=[('O', 'OpenWeather'), ('N', 'Parcelle')], max_length=1),
        ),
        migrations.AddField(
            model_name='noeud',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projet'),
        ),
    ]
